name: Deploy Package

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the release branch
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Prepare folders and Files
      #rename Samples folder, because in a working unity project we cannot have Samples~ folder, or Unity will just never import it.
        run: |
          mv Assets/ProxyEvents/Samples Assets/ProxyEvents/Samples~
          #The ProxyEvents project is set up to have a nice structure of all required resources under assets/ProxyEvents, therefore we will use all of the folder to publish
          mv Assets/ProxyEvents Packages/com.shakotis.proxyevents
          #mv Packages/manifest.json Packages/com.shakotis.proxyevents/manifest.json #This is not needed, because the manifest is in the root of the project?
          sed -i '1s/^\xEF\xBB\xBF//' Packages/com.shakotis.proxyevents/package.json
          cat Packages/com.shakotis.proxyevents/package.json | jq .
          git config --global user.email "kiber@shakotis.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Darth-Carrotpie/ProxyEvents.git
          git add Packages/com.shakotis.proxyevents
          git commit -m "Ensure package directory exists for subtree split"

      - name: Publish Unity package
        uses: cdmvision/action-upm-publish@v1
        with: 
          name: 'com.shakotis.proxyevents'
          upmBranch: 'upm'